-- Purchase orders from a service company to a parts supplier.
-- Visible only to the sending organization (not the supplier, not other shops).

CREATE TABLE IF NOT EXISTS public.purchase_orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id bigint NOT NULL REFERENCES public.organizations (id) ON DELETE CASCADE,
  supplier_organization_id bigint NULL REFERENCES public.organizations (id) ON DELETE SET NULL,
  supplier_name text NOT NULL,
  supplier_email text NULL,
  po_number text NULL,
  po_date date NULL DEFAULT CURRENT_DATE,
  needed_by date NULL,
  description text NULL,
  subtotal numeric(12,2) NULL DEFAULT 0,
  tax numeric(12,2) NULL DEFAULT 0,
  total numeric(12,2) NULL DEFAULT 0,
  status text NULL DEFAULT 'draft',
  po_data jsonb NULL DEFAULT '{}'::jsonb,
  created_by uuid NULL REFERENCES auth.users (id) ON DELETE SET NULL,
  sent_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS purchase_orders_org_idx
  ON public.purchase_orders (organization_id);

CREATE INDEX IF NOT EXISTS purchase_orders_supplier_idx
  ON public.purchase_orders (supplier_organization_id);

CREATE UNIQUE INDEX IF NOT EXISTS purchase_orders_org_number_uidx
  ON public.purchase_orders (organization_id, po_number)
  WHERE po_number IS NOT NULL AND po_number <> '';

ALTER TABLE public.purchase_orders ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS purchase_orders_sending_org_all ON public.purchase_orders;
CREATE POLICY purchase_orders_sending_org_all ON public.purchase_orders
  FOR ALL TO authenticated
  USING (
    organization_id = public.get_my_org_id()
    OR organization_id IN (SELECT public.my_membership_org_ids())
  )
  WITH CHECK (
    organization_id = public.get_my_org_id()
    OR organization_id IN (SELECT public.my_membership_org_ids())
  );

GRANT SELECT, INSERT, UPDATE, DELETE ON public.purchase_orders TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.purchase_orders_id_seq TO authenticated;

NOTIFY pgrst, 'reload schema';
