-- Customer locations: one business, more than one address.
--
-- Customers are organizations. The address columns on organizations stay the
-- primary-location snapshot so existing tickets, estimates, and invoices keep
-- reading the same fields. Additional addresses use public.locations, which
-- the generated schema already describes (name, address, city, state, zip,
-- phone, is_primary, organization_id). The web app did not read or write it.
--
-- This file is safe to re-run.
--
-- APPLY ON LIVE SUPABASE (SQL editor or CLI) before Add location can save.
-- Until then the customer screen keeps the single address and does not crash.
-- Logged-in reads that return no rows (RLS with nothing visible yet) do the same.
--
-- Existing location rows are not rewritten. is_primary flags already stored stay
-- as they are, including a customer that currently has more than one primary.
-- A trigger clears the other primaries only when a later insert or is_primary
-- update saves a row as primary, so another writer is not rejected.
--
--   1. Paste this file and Run.
--   2. Backfill check (only orgs that had zero location rows and an address):
--        select l.organization_id, l.name, l.address, l.city, l.state, l.is_primary
--        from public.locations l
--        join public.organizations o on o.id = l.organization_id
--        where o.type in ('customer', 'laser_clinic', 'laser_rental', 'laser_reseller')
--        order by l.organization_id desc
--        limit 20;
--   Preview and production do not apply this automatically.

CREATE TABLE IF NOT EXISTS public.locations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id bigint NOT NULL REFERENCES public.organizations (id) ON DELETE CASCADE,
  name text NOT NULL,
  address text,
  city text,
  state text,
  zip text,
  phone text,
  contact_name text,
  is_primary boolean NOT NULL DEFAULT false,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE public.locations ADD COLUMN IF NOT EXISTS contact_name text;
ALTER TABLE public.locations ADD COLUMN IF NOT EXISTS is_primary boolean DEFAULT false;
ALTER TABLE public.locations ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE public.locations ADD COLUMN IF NOT EXISTS address text;
ALTER TABLE public.locations ADD COLUMN IF NOT EXISTS city text;
ALTER TABLE public.locations ADD COLUMN IF NOT EXISTS state text;
ALTER TABLE public.locations ADD COLUMN IF NOT EXISTS zip text;
ALTER TABLE public.locations ADD COLUMN IF NOT EXISTS phone text;
ALTER TABLE public.locations ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

CREATE INDEX IF NOT EXISTS locations_organization_id_idx
  ON public.locations (organization_id);

-- Do not keep a unique "one primary" index. Another writer updates this table,
-- and a partial unique index would start rejecting those saves. Drop it if an
-- earlier draft of this file created it.
DROP INDEX IF EXISTS public.locations_one_primary_per_org;

-- When a row is saved as primary, clear the flag on the other rows for that
-- organization. Does not run against existing data by itself.
CREATE OR REPLACE FUNCTION public.locations_single_primary()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  IF NEW.is_primary IS TRUE THEN
    UPDATE public.locations
    SET is_primary = false
    WHERE organization_id = NEW.organization_id
      AND id IS DISTINCT FROM NEW.id
      AND is_primary IS TRUE;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS locations_single_primary ON public.locations;
CREATE TRIGGER locations_single_primary
  BEFORE INSERT OR UPDATE OF is_primary
  ON public.locations
  FOR EACH ROW
  EXECUTE FUNCTION public.locations_single_primary();

GRANT EXECUTE ON FUNCTION public.locations_single_primary() TO authenticated;

-- Existing single address becomes "Main office" only when that customer has
-- no location rows yet. Orgs that already have locations are left alone.
INSERT INTO public.locations (
  organization_id, name, address, city, state, zip, phone, is_primary
)
SELECT
  o.id,
  'Main office',
  NULLIF(btrim(o.address), ''),
  NULLIF(btrim(o.city), ''),
  NULLIF(btrim(o.state), ''),
  NULLIF(btrim(o.zip), ''),
  NULLIF(btrim(o.phone), ''),
  true
FROM public.organizations o
WHERE o.type IN ('customer', 'laser_clinic', 'laser_rental', 'laser_reseller')
  AND (
    NULLIF(btrim(COALESCE(o.address, '')), '') IS NOT NULL
    OR NULLIF(btrim(COALESCE(o.city, '')), '') IS NOT NULL
    OR NULLIF(btrim(COALESCE(o.state, '')), '') IS NOT NULL
    OR NULLIF(btrim(COALESCE(o.zip, '')), '') IS NOT NULL
  )
  AND NOT EXISTS (
    SELECT 1 FROM public.locations l WHERE l.organization_id = o.id
  );

-- Copy the legacy org contact onto the backfilled primary when that column exists.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'organizations'
      AND column_name = 'contact_name'
  ) THEN
    EXECUTE $sql$
      UPDATE public.locations l
      SET contact_name = NULLIF(btrim(o.contact_name), '')
      FROM public.organizations o
      WHERE o.id = l.organization_id
        AND l.is_primary IS TRUE
        AND l.name = 'Main office'
        AND (l.contact_name IS NULL OR btrim(l.contact_name) = '')
        AND NULLIF(btrim(COALESCE(o.contact_name, '')), '') IS NOT NULL
    $sql$;
  END IF;
END $$;

COMMENT ON TABLE public.locations IS
  'Addresses for an organization. A customer has one primary location (mirrors organizations address columns) plus optional extra locations.';

COMMENT ON COLUMN public.locations.contact_name IS
  'Optional person to ask for at this location. Directory person-roles stay on organizations.directory_contacts.';

-- Nullable pointer. Existing tickets keep customer_address and a NULL id.
DO $$
DECLARE
  loc_id_type text;
  col_type text;
BEGIN
  IF to_regclass('public.service_tickets') IS NULL THEN
    RETURN;
  END IF;

  SELECT data_type INTO loc_id_type
  FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'locations' AND column_name = 'id';

  IF loc_id_type IS NULL THEN
    RETURN;
  END IF;

  IF loc_id_type NOT IN ('bigint', 'integer', 'smallint') THEN
    loc_id_type := 'bigint';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'service_tickets'
      AND column_name = 'customer_location_id'
  ) THEN
    EXECUTE format(
      'ALTER TABLE public.service_tickets ADD COLUMN customer_location_id %s',
      loc_id_type
    );
  END IF;

  SELECT data_type INTO col_type
  FROM information_schema.columns
  WHERE table_schema = 'public'
    AND table_name = 'service_tickets'
    AND column_name = 'customer_location_id';

  IF col_type IS NOT NULL
     AND col_type = loc_id_type
     AND NOT EXISTS (
       SELECT 1 FROM pg_constraint WHERE conname = 'service_tickets_customer_location_id_fkey'
     ) THEN
    ALTER TABLE public.service_tickets
      ADD CONSTRAINT service_tickets_customer_location_id_fkey
      FOREIGN KEY (customer_location_id)
      REFERENCES public.locations (id)
      ON DELETE SET NULL;
  END IF;

  CREATE INDEX IF NOT EXISTS service_tickets_customer_location_id_idx
    ON public.service_tickets (customer_location_id);

  COMMENT ON COLUMN public.service_tickets.customer_location_id IS
    'Location chosen on New Service Call. NULL on older tickets; customer_address remains the snapshot.';
END $$;

-- Same access as contacts_service_company_linked_manage: the linked shop, or
-- someone whose active org / created_by is this organization.
CREATE OR REPLACE FUNCTION public.get_my_org_id()
RETURNS bigint
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT organization_id FROM public.user_profiles WHERE id = auth.uid() LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.user_owns_or_created_org(org_id bigint)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    org_id IS NOT NULL
    AND (
      org_id = (SELECT organization_id FROM public.user_profiles WHERE id = auth.uid() LIMIT 1)
      OR EXISTS (
        SELECT 1 FROM public.organizations o
        WHERE o.id = org_id AND o.created_by = auth.uid()
      )
    );
$$;

GRANT EXECUTE ON FUNCTION public.get_my_org_id() TO authenticated;
GRANT EXECUTE ON FUNCTION public.user_owns_or_created_org(bigint) TO authenticated;

ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS locations_service_company_linked_manage ON public.locations;
CREATE POLICY locations_service_company_linked_manage ON public.locations
  FOR ALL
  TO authenticated
  USING (
    public.user_owns_or_created_org(organization_id)
    OR EXISTS (
      SELECT 1
      FROM public.organization_customers oc
      WHERE oc.customer_organization_id = locations.organization_id
        AND oc.service_organization_id = public.get_my_org_id()
    )
  )
  WITH CHECK (
    public.user_owns_or_created_org(organization_id)
    OR EXISTS (
      SELECT 1
      FROM public.organization_customers oc
      WHERE oc.customer_organization_id = locations.organization_id
        AND oc.service_organization_id = public.get_my_org_id()
    )
  );

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.locations TO authenticated;

DO $$
DECLARE
  seq regclass;
BEGIN
  SELECT pg_get_serial_sequence('public.locations', 'id')::regclass INTO seq;
  IF seq IS NOT NULL THEN
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO authenticated', seq);
  END IF;
END $$;

NOTIFY pgrst, 'reload schema';

SELECT 'ok' AS status;
