-- Multi-org staffing: moonlight (home shop + FSE elsewhere) and move (leave A, join B).
--
-- user_profiles.organization_id stays the ACTIVE company so existing RLS
-- (customers, jobs, billing) does not leak across orgs.
-- organization_memberships is the durable (user, org, role) set.
--
-- APPLY ON LIVE SUPABASE (SQL Editor or CLI). Does not wipe orgs or users.

-- ---------------------------------------------------------------------------
-- 1) Memberships
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.organization_memberships (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  organization_id bigint NOT NULL REFERENCES public.organizations (id) ON DELETE CASCADE,
  role text NOT NULL DEFAULT 'fse',
  is_home boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, organization_id)
);

CREATE INDEX IF NOT EXISTS organization_memberships_org_idx
  ON public.organization_memberships (organization_id);

CREATE INDEX IF NOT EXISTS organization_memberships_user_idx
  ON public.organization_memberships (user_id);

ALTER TABLE public.user_profiles
  ADD COLUMN IF NOT EXISTS active_organization_id bigint REFERENCES public.organizations (id);

COMMENT ON TABLE public.organization_memberships IS
  'Per-org roles. user_profiles.organization_id is the active org for RLS; this table holds every shop the user belongs to.';

-- Backfill one membership per existing profile pointer. Founder-ish roles are home.
INSERT INTO public.organization_memberships (user_id, organization_id, role, is_home)
SELECT
  p.id,
  p.organization_id,
  COALESCE(NULLIF(TRIM(p.role), ''), 'fse'),
  lower(COALESCE(p.role, '')) IN (
    'admin', 'company_admin', 'owner', 'parts_supplier', 'supplier'
  )
FROM public.user_profiles p
WHERE p.organization_id IS NOT NULL
ON CONFLICT (user_id, organization_id) DO NOTHING;

UPDATE public.user_profiles
SET active_organization_id = organization_id
WHERE organization_id IS NOT NULL
  AND active_organization_id IS NULL;

-- ---------------------------------------------------------------------------
-- 2) Keep a membership row whenever a profile is first linked to an org
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.user_profiles_sync_membership()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  home boolean;
BEGIN
  IF NEW.organization_id IS NULL THEN
    RETURN NEW;
  END IF;

  home := lower(COALESCE(NEW.role, '')) IN (
    'admin', 'company_admin', 'owner', 'parts_supplier', 'supplier'
  );

  INSERT INTO public.organization_memberships (user_id, organization_id, role, is_home)
  VALUES (NEW.id, NEW.organization_id, COALESCE(NULLIF(TRIM(NEW.role), ''), 'fse'), home)
  ON CONFLICT (user_id, organization_id) DO UPDATE
    SET updated_at = now(),
        -- Never demote a home/founder row from a later profile pointer change
        is_home = public.organization_memberships.is_home
                  OR EXCLUDED.is_home,
        role = CASE
          WHEN public.organization_memberships.is_home THEN public.organization_memberships.role
          ELSE EXCLUDED.role
        END;

  IF NEW.active_organization_id IS NULL THEN
    NEW.active_organization_id := NEW.organization_id;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS user_profiles_sync_membership ON public.user_profiles;
CREATE TRIGGER user_profiles_sync_membership
  BEFORE INSERT OR UPDATE OF organization_id, role, active_organization_id
  ON public.user_profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.user_profiles_sync_membership();

-- ---------------------------------------------------------------------------
-- 3) Guard: allow switching active org to a membership; still block steal
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.user_profiles_guard_identity()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  actor uuid;
  own_created boolean;
  invited boolean;
  member_of_new boolean;
  member_role text;
  locked_roles text[] := ARRAY[
    'admin', 'company_admin', 'owner', 'customer', 'parts_supplier',
    'service_manager', 'dispatcher', 'scheduler', 'billing_manager'
  ];
BEGIN
  actor := auth.uid();
  IF actor IS NULL THEN
    RETURN NEW;
  END IF;

  IF TG_OP = 'INSERT' AND NEW.id IS DISTINCT FROM actor THEN
    RAISE EXCEPTION 'user_profiles insert must be your own row';
  END IF;

  IF TG_OP = 'UPDATE' AND NEW.id IS DISTINCT FROM OLD.id THEN
    RAISE EXCEPTION 'user_profiles id cannot be changed';
  END IF;

  IF TG_OP = 'UPDATE'
     AND NEW.organization_id IS DISTINCT FROM OLD.organization_id THEN
    IF NEW.organization_id IS NOT NULL THEN
      SELECT EXISTS (
        SELECT 1 FROM public.organization_memberships m
        WHERE m.user_id = actor AND m.organization_id = NEW.organization_id
      ) INTO member_of_new;
      IF member_of_new THEN
        -- Active-org switch (or first activate of a membership).
        NULL;
      ELSE
        IF OLD.organization_id IS NOT NULL THEN
          RAISE EXCEPTION 'organization_id cannot be changed by the client';
        END IF;
        SELECT EXISTS (
          SELECT 1 FROM public.organizations o
          WHERE o.id = NEW.organization_id AND o.created_by = actor
        ) INTO own_created;
        SELECT EXISTS (
          SELECT 1 FROM public.engineer_invitations i
          WHERE i.organization_id = NEW.organization_id
            AND lower(i.email) = lower(COALESCE(NEW.email, ''))
            AND COALESCE(i.accepted, false) = false
        ) INTO invited;
        IF NOT own_created AND NOT invited THEN
          RAISE EXCEPTION 'cannot attach profile to an organization you did not create or were not invited to';
        END IF;
      END IF;
    ELSE
      -- Clearing active org is allowed only when they have no memberships left
      -- (after leave) or they still have memberships and a later write will set it.
      NULL;
    END IF;
  END IF;

  IF NEW.organization_id IS NOT NULL
     AND TG_OP = 'INSERT' THEN
    SELECT EXISTS (
      SELECT 1 FROM public.organization_memberships m
      WHERE m.user_id = actor AND m.organization_id = NEW.organization_id
    ) INTO member_of_new;
    SELECT EXISTS (
      SELECT 1 FROM public.organizations o
      WHERE o.id = NEW.organization_id AND o.created_by = actor
    ) INTO own_created;
    SELECT EXISTS (
      SELECT 1 FROM public.engineer_invitations i
      WHERE i.organization_id = NEW.organization_id
        AND lower(i.email) = lower(COALESCE(NEW.email, ''))
        AND COALESCE(i.accepted, false) = false
    ) INTO invited;
    IF NOT member_of_new AND NOT own_created AND NOT invited THEN
      RAISE EXCEPTION 'cannot attach profile to an organization you did not create or were not invited to';
    END IF;
  END IF;

  IF TG_OP = 'UPDATE'
     AND NEW.role IS DISTINCT FROM OLD.role THEN
    SELECT m.role INTO member_role
    FROM public.organization_memberships m
    WHERE m.user_id = actor
      AND m.organization_id = COALESCE(NEW.organization_id, OLD.organization_id)
    LIMIT 1;

    IF member_role IS NOT NULL AND lower(NEW.role) = lower(member_role) THEN
      -- Role follows the membership of the (new) active org.
      NULL;
    ELSIF OLD.organization_id IS NOT NULL THEN
      SELECT EXISTS (
        SELECT 1 FROM public.organizations o
        WHERE o.id = OLD.organization_id AND o.created_by = actor
      ) INTO own_created;

      IF OLD.role IS NOT NULL AND lower(OLD.role) = ANY (locked_roles) THEN
        RAISE EXCEPTION 'role cannot be changed by the client once set';
      END IF;

      IF NOT own_created THEN
        RAISE EXCEPTION 'role cannot be changed by the client once set';
      END IF;
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION public.user_profiles_guard_identity() IS
  'Blocks steal/self-attach. Allows switching organization_id/role to an existing organization_memberships row.';

-- ---------------------------------------------------------------------------
-- 4) RLS on memberships
-- ---------------------------------------------------------------------------
ALTER TABLE public.organization_memberships ENABLE ROW LEVEL SECURITY;

-- SECURITY DEFINER so SELECT policies can see teammate rows without recursion.
CREATE OR REPLACE FUNCTION public.my_membership_org_ids()
RETURNS SETOF bigint
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT organization_id
  FROM public.organization_memberships
  WHERE user_id = auth.uid();
$$;

DROP POLICY IF EXISTS organization_memberships_select_own ON public.organization_memberships;
CREATE POLICY organization_memberships_select_own ON public.organization_memberships
  FOR SELECT
  TO authenticated
  USING (
    user_id = auth.uid()
    OR organization_id IN (SELECT public.my_membership_org_ids())
  );

DROP POLICY IF EXISTS organization_memberships_insert_own_home ON public.organization_memberships;
CREATE POLICY organization_memberships_insert_own_home ON public.organization_memberships
  FOR INSERT
  TO authenticated
  WITH CHECK (
    user_id = auth.uid()
    AND (
      EXISTS (
        SELECT 1 FROM public.organizations o
        WHERE o.id = organization_id AND o.created_by = auth.uid()
      )
      OR EXISTS (
        SELECT 1 FROM public.engineer_invitations i
        WHERE i.organization_id = organization_id
          AND lower(i.email) = lower((SELECT email FROM public.user_profiles WHERE id = auth.uid()))
          AND COALESCE(i.accepted, false) = false
      )
    )
  );

DROP POLICY IF EXISTS organization_memberships_delete_own ON public.organization_memberships;
CREATE POLICY organization_memberships_delete_own ON public.organization_memberships
  FOR DELETE
  TO authenticated
  USING (user_id = auth.uid() AND is_home = false);

-- Team admins of the active org can read roster via the org-scoped select above.
-- Writes that add moonlight memberships go through service role / SECURITY DEFINER RPCs.

-- ---------------------------------------------------------------------------
-- 5) RPCs (web + Android WebView). Same login; active org drives RLS.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.switch_active_organization(p_organization_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  actor uuid;
  mem public.organization_memberships%ROWTYPE;
BEGIN
  actor := auth.uid();
  IF actor IS NULL THEN
    RAISE EXCEPTION 'not signed in';
  END IF;

  SELECT * INTO mem
  FROM public.organization_memberships
  WHERE user_id = actor AND organization_id = p_organization_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'not a member of that organization';
  END IF;

  UPDATE public.user_profiles
  SET
    organization_id = mem.organization_id,
    active_organization_id = mem.organization_id,
    role = mem.role,
    updated_at = now()
  WHERE id = actor;

  RETURN jsonb_build_object(
    'ok', true,
    'organization_id', mem.organization_id,
    'role', mem.role,
    'is_home', mem.is_home
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.leave_organization(p_organization_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  actor uuid;
  mem public.organization_memberships%ROWTYPE;
  next_mem public.organization_memberships%ROWTYPE;
  was_active bigint;
BEGIN
  actor := auth.uid();
  IF actor IS NULL THEN
    RAISE EXCEPTION 'not signed in';
  END IF;

  SELECT * INTO mem
  FROM public.organization_memberships
  WHERE user_id = actor AND organization_id = p_organization_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'not a member of that organization';
  END IF;

  SELECT organization_id INTO was_active
  FROM public.user_profiles
  WHERE id = actor;

  DELETE FROM public.organization_memberships
  WHERE user_id = actor AND organization_id = p_organization_id;

  SELECT * INTO next_mem
  FROM public.organization_memberships
  WHERE user_id = actor
  ORDER BY is_home DESC, created_at ASC
  LIMIT 1;

  IF was_active IS NOT DISTINCT FROM p_organization_id THEN
    IF next_mem.organization_id IS NOT NULL THEN
      UPDATE public.user_profiles
      SET
        organization_id = next_mem.organization_id,
        active_organization_id = next_mem.organization_id,
        role = next_mem.role,
        updated_at = now()
      WHERE id = actor;
    ELSE
      UPDATE public.user_profiles
      SET
        organization_id = NULL,
        active_organization_id = NULL,
        updated_at = now()
      WHERE id = actor;
    END IF;
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'left_organization_id', p_organization_id,
    'organization_id', next_mem.organization_id,
    'role', next_mem.role,
    'account_kept', true
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.accept_team_invite(p_invite_id bigint, p_leave_organization_id bigint DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  actor uuid;
  actor_email text;
  inv public.engineer_invitations%ROWTYPE;
  home_mem public.organization_memberships%ROWTYPE;
  has_any boolean;
BEGIN
  actor := auth.uid();
  IF actor IS NULL THEN
    RAISE EXCEPTION 'not signed in';
  END IF;

  SELECT email INTO actor_email FROM public.user_profiles WHERE id = actor;
  IF actor_email IS NULL THEN
    SELECT email INTO actor_email FROM auth.users WHERE id = actor;
  END IF;

  SELECT * INTO inv
  FROM public.engineer_invitations
  WHERE id = p_invite_id
    AND lower(email) = lower(actor_email);

  IF NOT FOUND THEN
    RAISE EXCEPTION 'invitation not found';
  END IF;

  IF p_leave_organization_id IS NOT NULL THEN
    SELECT * INTO home_mem
    FROM public.organization_memberships
    WHERE user_id = actor AND organization_id = p_leave_organization_id;

    IF FOUND AND (home_mem.is_home OR lower(home_mem.role) IN (
      'admin', 'company_admin', 'owner', 'parts_supplier', 'supplier'
    )) THEN
      RAISE EXCEPTION 'founder/owner of their home shop cannot be removed by another company invite';
    END IF;
  END IF;

  INSERT INTO public.organization_memberships (user_id, organization_id, role, is_home)
  VALUES (
    actor,
    inv.organization_id,
    COALESCE(NULLIF(TRIM(inv.role), ''), 'fse'),
    false
  )
  ON CONFLICT (user_id, organization_id) DO UPDATE
    SET updated_at = now(),
        role = CASE
          WHEN public.organization_memberships.is_home THEN public.organization_memberships.role
          ELSE EXCLUDED.role
        END;

  UPDATE public.engineer_invitations
  SET accepted = true, accepted_at = now()
  WHERE id = inv.id;

  IF p_leave_organization_id IS NOT NULL THEN
    DELETE FROM public.organization_memberships
    WHERE user_id = actor
      AND organization_id = p_leave_organization_id
      AND is_home = false
      AND lower(role) NOT IN ('admin', 'company_admin', 'owner', 'parts_supplier', 'supplier');
  END IF;

  SELECT EXISTS (
    SELECT 1 FROM public.organization_memberships WHERE user_id = actor
  ) INTO has_any;

  -- First membership activates; moonlight keeps the current active/home org.
  IF NOT EXISTS (
    SELECT 1 FROM public.user_profiles
    WHERE id = actor AND organization_id IS NOT NULL
  ) THEN
    UPDATE public.user_profiles
    SET
      organization_id = inv.organization_id,
      active_organization_id = inv.organization_id,
      role = COALESCE(NULLIF(TRIM(inv.role), ''), 'fse'),
      updated_at = now()
    WHERE id = actor;
  ELSIF p_leave_organization_id IS NOT NULL THEN
    UPDATE public.user_profiles
    SET
      organization_id = inv.organization_id,
      active_organization_id = inv.organization_id,
      role = COALESCE(NULLIF(TRIM(inv.role), ''), 'fse'),
      updated_at = now()
    WHERE id = actor
      AND organization_id IS NOT DISTINCT FROM p_leave_organization_id;
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'organization_id', inv.organization_id,
    'role', COALESCE(NULLIF(TRIM(inv.role), ''), 'fse'),
    'moonlight', has_any
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.my_membership_org_ids() TO authenticated;
GRANT EXECUTE ON FUNCTION public.switch_active_organization(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.leave_organization(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.accept_team_invite(bigint, bigint) TO authenticated;

NOTIFY pgrst, 'reload schema';
